# =======================================
# Site Information Setting
# =======================================

# Site create time
since: 2017

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Menu settings
menu:
  home: /
  archive: /archives
  # categories: /categories
  tags: /tags
  # about: /about

# Assets
css: css
js: js
img: img
lib: lib
